Repository measure-your-life-squad/measure-your-life, pull requests merged in 2020-05, with the labels that each got.

#23 add flake8 compliance check to CI
  .flake8
  .travis.yml
  api_backend_server/web_app/api_utils/__init__.py
  cicd_requirements.txt
Labels: continuous integration

#24 add email verification mechanism
  .travis.yml
  api_backend_server/README.md
  api_backend_server/requirements.txt
  api_backend_server/web_app/api_utils/__init__.py
  api_backend_server/web_app/api_utils/auth_utils.py
  api_backend_server/web_app/api_utils/email_utils.py
  api_backend_server/web_app/apis/activities.py
  api_backend_server/web_app/apis/users.py
  api_backend_server/web_app/models/__init__.py
  api_backend_server/web_app/openapi.yaml
  api_backend_server/web_app/server.py
  api_backend_server/web_app/templates/activate_email.html
  docker-compose.yml
  mongo_db/init_db.js
Labels: enhancement

#25 Email added to register form, flutter version upgrade
  mobile_app/.packages
  mobile_app/ios/Runner.xcodeproj/project.pbxproj
  mobile_app/lib/providers/user_repository.dart
  mobile_app/lib/widgets/sign_up_view.dart
  mobile_app/pubspec.lock
Labels: enhancement

#22 adding first unittest part
  api_backend_server/tests/conftest.py
  api_backend_server/tests/unit_tests/test_activities_api.py
  api_backend_server/web_app/api_utils/auth_utils.py
  api_backend_server/web_app/apis/activities.py
  api_backend_server/web_app/apis/categories.py
  api_backend_server/web_app/apis/root.py
  api_backend_server/web_app/apis/users.py
  api_backend_server/web_app/database.py
  api_backend_server/web_app/server.py
  cicd_requirements.txt
Labels: testing

#27 Feature/edit delete activities api
  api_backend_server/web_app/apis/activities.py
  api_backend_server/web_app/models/__init__.py
  api_backend_server/web_app/openapi.yaml
Labels: enhancement

#20 write integration tests for users api
  api_backend_server/tests/integration_tests/integration_utils.py
  api_backend_server/tests/integration_tests/test_activities_apis.py
  api_backend_server/tests/integration_tests/test_hello_webserver.py
  api_backend_server/tests/integration_tests/test_users_apis.py
Labels: testing

#29 render html responses for account confirmations
  api_backend_server/web_app/api_utils/email_utils.py
  api_backend_server/web_app/apis/users.py
  api_backend_server/web_app/openapi.yaml
  api_backend_server/web_app/static/css/.DS_Store
  api_backend_server/web_app/static/css/animate.css
  api_backend_server/web_app/static/css/bootstrap.css
  api_backend_server/web_app/static/css/bootstrap.css.map
  api_backend_server/web_app/static/css/flexslider.css
  api_backend_server/web_app/static/css/icomoon.css
  api_backend_server/web_app/static/css/magnific-popup.css
  api_backend_server/web_app/static/css/owl.carousel.min.css
  api_backend_server/web_app/static/css/owl.theme.default.min.css
  api_backend_server/web_app/static/css/style.css
  api_backend_server/web_app/static/css/style.css.map
  api_backend_server/web_app/static/fonts/.DS_Store
  api_backend_server/web_app/static/fonts/bootstrap/.DS_Store
  api_backend_server/web_app/static/fonts/bootstrap/glyphicons-halflings-regular.eot
  api_backend_server/web_app/static/fonts/bootstrap/glyphicons-halflings-regular.svg
  api_backend_server/web_app/static/fonts/bootstrap/glyphicons-halflings-regular.ttf
  api_backend_server/web_app/static/fonts/bootstrap/glyphicons-halflings-regular.woff
  api_backend_server/web_app/static/fonts/bootstrap/glyphicons-halflings-regular.woff2
  api_backend_server/web_app/static/fonts/icomoon/.DS_Store
  api_backend_server/web_app/static/fonts/icomoon/icomoon.eot
  api_backend_server/web_app/static/fonts/icomoon/icomoon.svg
  api_backend_server/web_app/static/fonts/icomoon/icomoon.ttf
  api_backend_server/web_app/static/fonts/icomoon/icomoon.woff
  api_backend_server/web_app/static/images/.DS_Store
  api_backend_server/web_app/static/images/cover_img_1.jpg
  api_backend_server/web_app/static/js/.DS_Store
  api_backend_server/web_app/static/js/bootstrap.min.js
  api_backend_server/web_app/static/js/google_map.js
  api_backend_server/web_app/static/js/jquery.countTo.js
  api_backend_server/web_app/static/js/jquery.easing.1.3.js
  api_backend_server/web_app/static/js/jquery.magnific-popup.min.js
  api_backend_server/web_app/static/js/jquery.mb.YTPlayer.min.js
  api_backend_server/web_app/static/js/jquery.min.js
  api_backend_server/web_app/static/js/jquery.stellar.min.js
  api_backend_server/web_app/static/js/jquery.waypoints.min.js
  api_backend_server/web_app/static/js/magnific-popup-options.js
  api_backend_server/web_app/static/js/main.js
  api_backend_server/web_app/static/js/modernizr-2.6.2.min.js
  api_backend_server/web_app/static/js/owl.carousel.min.js
  api_backend_server/web_app/static/js/respond.min.js
  api_backend_server/web_app/templates/account_confirmation.html
Labels: enhancement

#30 include account confirmation information in login response
  api_backend_server/web_app/api_utils/auth_utils.py
  api_backend_server/web_app/apis/users.py
  api_backend_server/web_app/models/__init__.py
  api_backend_server/web_app/openapi.yaml
Labels: enhancement

#41 integrate daily averages
  api_backend_server/web_app/apis/activities.py
  api_backend_server/web_app/apis/statistics.py
  api_backend_server/web_app/openapi.yaml
  mobile_app/lib/models/statistics.dart
Labels: enhancement

#53 Feature/update readme for backend
  1.png
  2.png
  3.png
  README.md
  api_backend_server/README.md
  api_backend_server/tests/integration_tests/test_activities_apis.py
  api_backend_server/web_app/models/__init__.py
  api_backend_server/web_app/openapi.yaml
  home_screen.png
  mongo_db/README.md
  new_activity_screen.png
Labels: documentation

#54 Feature/add test scenarios
  README.md
  test_scenarios/Dodawanie-aktywności-cześć-2.md
  test_scenarios/Dodawanie-aktywności-część-1.md
  test_scenarios/Edycja-aktywności.md
  test_scenarios/Logowanie.md
  test_scenarios/Odzyskiwanie-hasła.md
  test_scenarios/README.md
  test_scenarios/Rejestracja.md
  test_scenarios/Statystyki-aktywności.md
  test_scenarios/Usuwanie-aktywności.md
Labels: testing

#55 adding more tests for backend
  api_backend_server/tests/unit_tests/test_activities_api.py
  api_backend_server/tests/unit_tests/test_statistics.py
  api_backend_server/tests/unit_tests/test_users.py
Labels: testing
